services:
  blog:
    environment:
      - PUB_PLAUSIBLE_URL=${PUB_PLAUSIBLE_URL:-https://plausible.example.com}
      - PUB_HOSTNAME=${PUB_HOSTNAME:-example.com}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUB_PLAUSIBLE_URL: ${PUB_PLAUSIBLE_URL:-https://plausible.example.com}
        PUB_HOSTNAME: ${PUB_HOSTNAME:-example.com}
    ports:
      - "28473:80"